[project]
name = "meetings"
version = "0.0.1"
description = ""
authors = [
    {name = "joegasewicz",email = "joegasewicz@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "wxpython (>=4.3.1,<5.0.0)",
    "tornado (>=6.5.8,<7.0.0)",
    "marshmallow (>=4.3.1,<5.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "alembic (>=1.19.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pylint (>=4.0.8,<5.0.0)"
]
